name: CI/CD Render API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST "$RENDER_DEPLOY_HOOK_URL"
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_GRANT_TYPE: ${{ secrets.AUTH0_GRANT_TYPE }}
          RATE_LIMIT_MAX: ${{ secrets.RATE_LIMIT_MAX }}
          RATE_LIMIT_TIME_WINDOW: ${{ secrets.RATE_LIMIT_TIME_WINDOW }}
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
